### ISSUE TITLE
Don't put abstracts as type fields

### ISSUE THREAD

**Issue by tbreloff** [REX-Computing/unumjl#4]
I just noticed that your SuperInt is a Union type, which is abstract, but you have it in your core Unum type:

```
immutable Unum{ESS, FSS} <: Utype
  ...
  fraction::SuperInt
  ...
end
```

If you need this to be a Union type, it should be a parameter to improve performance:

```
immutable Unum{ESS, FSS, SI<:SuperInt} <: Utype
  ...
  fraction::SI
  ...
end
```

**Comment by ityonemo** [comment]
Are you sure there's a performance penalty here?  I'm not 100% versed in the exact architecture that Julia JITs into...

I'm loathe to add another type parameter.  The FSS directly determines the type for fraction and that doesn't change within any given type.   Maybe it would be better to just leave it untyped.

**Comment by tbreloff** [comment]
I'm 99% sure there will be a penalty... and it will likely be worse if you leave the type annotation off (though probably it will be the same penalty either way).  You should read through the [performance tips](http://docs.julialang.org/en/release-0.4/manual/performance-tips/)... not sure if this specifically is in there but it's all stuff you should be aware of.

In terms of performance, it should be possible for unums to beat Float128, and certainly BigFloats...  a few small tweaks can sometimes make a big difference.

**Comment by tbreloff** [comment]
The thing to always consider is type stability... think whether the compiler will be able to guarantee whether a variable/calculation is a certain concrete type.  If not, it needs to be boxed with special handling.  If that happens inside a tight inner loop it'll kill performance. (realistically, everything in this repo will potentially be inside tight inner loops)  In this case it will get a type Unum, but it can't know the type of the superint, so everything that touches will be type-unstable.

**Comment by ityonemo** [comment]
I think the biggest concern is type stability with _function calls_.  In the directory_reorg branch (which is rapidly turning into a major refactor), I'm breaking out all of the functions into two versions, one for Array{Uint64} and the other for just Uint64.  I think I want to table this modification until after the directory_reorg refactor.  We can fork a branch and test this theory relatively easily.   I'm going to think about whether there is a better way to do this in general.

**Comment by tbreloff** [comment]
Ok you seem pretty sure, so I'll wait to see.  Just remember that parameterizing is best for this sort of thing. (or you could just have 2 separate types)

**Comment by ityonemo** [comment]
Yes, I think two types makes more sense, and you could potentially alias them somehow.

**Comment by dpsanders** [comment]
I agree with @tbreloff, you definitely don't want abstract types (even unions) inside type declarations. This prevents essential compiler optimizations (basically, the ability to store objects of the type in a contiguous way in memory, IIUC).

**Comment by ityonemo** [comment]
OK.  So to square this circle, this is what  I'm going to propose:

https://gist.github.com/ityonemo/fd72b2f632500bf77a3d

This will allow the Unum{ESS,FSS} constructor to generally be a 'human-interface-ready' version.  Data preparation and all that are "okay to be slow" - I think - but if performance in that is really critical, then direct use of the Unum_Small and Unum_Variable types would be recommended.  convert() functions will be able to "figure out which should be used" with not much of a problem.

Two things, 1) h-layer stuff would be agnostic to the underlying implementation (goes with h-layer doesn't have to be as fassst), and 2) outputting using display() which I badly have to fix anyways, will output strings using Unum{ESS,FSS}(...) syntax, so that copy/paste will still result in a valid constructor string.

**Comment by ityonemo** [comment]
Type system has been completely revamped for new version.
